// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//        sidebar
//       <body>{children}</body>
//     </html>
//   )
// }


const RootLayout = ({children}: {
   children: React.ReactNode
    }) => {
     return (
         <main>
          {children}
         </main>
          
     )
}

export default RootLayout
